### ISSUE TITLE
可以展示一下contentLength

### ISSUE THREAD

**Issue by z2p** [ScriptKid-Beta/WebBatchRequest#1]

**Comment by ScriptKid-Beta** [comment]
下个版本更新展示~，感谢师傅的意见~

**Comment by ScriptKid-Beta** [comment]
已在v1.1版本展示：https://github.com/ScriptKid-Beta/WebBatchRequest/releases/tag/v1.1
![image](https://user-images.githubusercontent.com/62375108/122643506-ba628e80-d142-11eb-9315-9efc8445d203.png)
