### ISSUE TITLE
跑大量url的时候，会剩余几个不跑了

### ISSUE THREAD

**Issue by Tab0XTang** [ScriptKid-Beta/WebBatchRequest#13]
例如这样
![image](https://user-images.githubusercontent.com/96402640/146714892-f522067f-d701-4781-aea3-30b81bff4007.png)
长时间卡在这里

**Comment by ScriptKid-Beta** [comment]
这是因为有几个目标站点响应时间过长(基本是无法访问的了)，需要等待一段时间~

**Comment by Tab0XTang** [comment]
好的谢谢
