### ISSUE TITLE
结果超过100条时，无法正常导出

### ISSUE THREAD

**Issue by handbye** [ScriptKid-Beta/WebBatchRequest#2]

**Comment by ScriptKid-Beta** [comment]
感谢师傅反馈，已在下个版本进行了修复~

**Comment by ScriptKid-Beta** [comment]
感谢师傅反馈，经测试并非数量上导致，已在下个版本进行了修复~
![image](https://user-images.githubusercontent.com/62375108/122533589-55306f80-d054-11eb-8e69-a1595399db6c.png)

**Comment by ScriptKid-Beta** [comment]
已在v1.1版本修复：https://github.com/ScriptKid-Beta/WebBatchRequest/releases/tag/v1.1
