### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by rainto** [ScriptKid-Beta/WebBatchRequest#3]
不小心双击结果中的某一行就会闪退。

**Comment by ScriptKid-Beta** [comment]
双击结果列表是用默认浏览器打开目标，还请师傅详情描述

**Comment by ScriptKid-Beta** [comment]
可关注最新版本：https://github.com/ScriptKid-Beta/WebBatchRequest/releases/

**Comment by ScriptKid-Beta** [comment]
可尝试最新版本：https://github.com/ScriptKid-Beta/WebBatchRequest/releases/
