### ISSUE TITLE
批量导出请求结果需求

### ISSUE THREAD

**Issue by NewBeginning6** [ScriptKid-Beta/WebBatchRequest#4]
批量导出请求结果需求

**Comment by ScriptKid-Beta** [comment]
v1.0版本+已经支持结果数据的导出
- [x] 支持数据的导入、导出
菜单栏  >> 文件 >> 导出结果
![image](https://user-images.githubusercontent.com/62375108/123042217-0e15f600-d429-11eb-9946-b35968b6c000.png)
