### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by CIA-ai** [ScriptKid-Beta/WebBatchRequest#5]
师傅，请问下运行不了，怎么解决呢

**Comment by ScriptKid-Beta** [comment]
还请师傅详细描述，当前JAVA版本，具体怎么无法运行等？

**Comment by CIA-ai** [comment]
> 还请师傅详细描述，当前JAVA版本，具体怎么无法运行等？

java version "1.8.0_211"
报错提示：错误: 找不到或无法加载主类 Gui.java

**Comment by ScriptKid-Beta** [comment]
是当前版本吗？
https://github.com/ScriptKid-Beta/WebBatchRequest/releases/tag/v1.2

**Comment by CIA-ai** [comment]
> 是当前版本吗？
> https://github.com/ScriptKid-Beta/WebBatchRequest/releases/tag/v1.2

可以了，感谢
