### ISSUE TITLE
建议增加几个功能

### ISSUE THREAD

**Issue by IGbaolan** [ScriptKid-Beta/WebBatchRequest#6]
1、结果出来之后，在右侧点击一条能看到详细请求和返回数据包
1、能设置url，不知道是不是我没用好，我没找到get如何设置uri 即url中ip后面的部门，我现在每次都是在target设置 不太方便。

**Comment by ScriptKid-Beta** [comment]
返回的body，可在结果列表-右键菜单中预览body；
不太明白描述的第二个；

**Comment by IGbaolan** [comment]
就是能否加一个url输入框，url在这个输入框中输入，targets每次只需要http://ip/即可，不用再targets后面加路径。

**Comment by ScriptKid-Beta** [comment]
是要为多个target追加相同路径吗？

**Comment by IGbaolan** [comment]
对的，不然的话，设计的初衷是在Header中设置路径吗，我理解可以参考下postman这种工具的设计，工具整体很好用啊 支持下，还有个就是status中 排序顺序为 `无法访问`-->`200` --> `404` --> `500`,后面的没问题，`无法访问`是否可以默认放在最后。

**Comment by ScriptKid-Beta** [comment]
师傅暂时可以用Execl等工具进行数据处理后导入目标，下个版本将考虑师傅的需求意见~

**Comment by IGbaolan** [comment]
好，先star了~

**Comment by ScriptKid-Beta** [comment]
已在v1.3版本中支持 https://github.com/ScriptKid-Beta/WebBatchRequest/releases/tag/v1.3
![image](https://user-images.githubusercontent.com/62375108/126458501-d8dbcb3e-e0b9-4aaa-acc6-90926862fcdd.png)
