### ISSUE TITLE
大佬好，当我使用泛微oa的资产进行批量请求时，无论我是否勾选302，都不会扫描出title，这是为什么呢

### ISSUE THREAD

**Issue by Ma1Dong** [ScriptKid-Beta/WebBatchRequest#7]
![图片](https://user-images.githubusercontent.com/52943794/127208563-90bcc77d-48ba-40ce-9112-84795c918130.png)

**Comment by ScriptKid-Beta** [comment]
经测试，泛微OA系统网站初始<title>为空，之后解析<script>再通过document.title进行设置title。所以获取了title为空的情况，下个版本将考虑该问题~
![image](https://user-images.githubusercontent.com/62375108/127254038-95789aa5-b9d4-4129-af6f-c810c24e2b9a.png)
![image](https://user-images.githubusercontent.com/62375108/127253652-db0264a4-5454-41d5-932c-62c34f0f25c2.png)
![image](https://user-images.githubusercontent.com/62375108/127253710-77e1af6d-420c-43b7-8618-e2369eb1a980.png)

**Comment by Ma1Dong** [comment]
大佬牛逼

**Comment by ScriptKid-Beta** [comment]
已在v1.4版本中支持 https://github.com/ScriptKid-Beta/WebBatchRequest/releases/tag/v1.4
