### ISSUE TITLE
自定义host头无效

### ISSUE THREAD

**Issue by IGbaolan** [ScriptKid-Beta/WebBatchRequest#8]
![微信截图_20211109114330](https://user-images.githubusercontent.com/5028716/140858229-cf542ee4-3c5b-4517-9042-b1032a81b7d0.png)

自定义host 头信息，代理抓包后发现并未更改。

**Comment by ScriptKid-Beta** [comment]
感谢师傅反馈，已在v1.4版本中支持 https://github.com/ScriptKid-Beta/WebBatchRequest/releases/tag/v1.4
![image](https://user-images.githubusercontent.com/62375108/141072608-e29f605e-2604-463f-93a2-6ef17469c4f5.png)
